### ISSUE TITLE
Projects limits

### ISSUE THREAD

**Issue by bendavis78** [IBM/taxinomitis#166]
As I understand, there is a limit of two projects per account -- I'm assuming this is because they're tied directly to Watson resources (I haven't looked through the code to see how it works yet, so correct me if I'm wrong). 

It would be great if students could retain their project data in some way. A student may want to keep a project around for their own portfolio, or to reflect on something they've done in the past. 

In essence, a project is simply configuration data and training examples. Re-training a model is easy, but adding training data is more time consuming (if it was done manually), so it's a bit painful to have to delete this work when you want to start a new project.

I think there are a couple of approaches to solve this:

1) Add download / upload functionality (similar to scratch) for training data and other project settings. 
2) De-couple the project from Watson resources by "deactivating" projects, and "activating" a project when needed.

Option 2 would be ideal, and is essentially a more automated version of option 1. The project data would be stored on ML4K, and the project would need to be re-activated simply by clicking a button.

**Comment by dalelane** [comment]
Closing as I think all of this already exists, but shout if you think there is still something needed.

The number-of-projects limit isn't related to Watson, it was just a way of helping me to keep some control over my MySQL hosting costs, as I'm trying to run the site on a shoestring budget! :-) 

The limit is configurable per class, and there is a message on the "[Restrictions](https://machinelearningforkids.co.uk/#!/teacher/restrictions)" page inviting teachers to ask if they need any limit changed. I'm happy to change the limits (within reason!) for a class to better support particular requirements. I get a few such requests a day, and so far have never said no to any of them. Making this a manual "email me" thing rather than automating it was originally intended to limit this to the schools that really need it. 

This is separate from the Watson resources/models. The "Learn & Test" page has a "Delete machine learning model" button which deletes any Watson resources associated with a project, while not deleting any training data from Machine Learning for Kids. This is intended to allow students to create more projects than they have API keys for, as they can just retrain models as needed from their existing/previous training data. 

In fact, most classes/schools don't even need to do this, as this is done automatically after a configurable time window. The [Restrictions](To help you avoid the limits for number of machine learning models) page has a way to specify the time window after which the Watson model is deleted, in the "To help you avoid the limits for number of machine learning models" section. This is described in more detail in the [Help](https://machinelearningforkids.co.uk/help) page, in the "Why are machine learning models automatically deleted?" FAQ.

**Comment by bendavis78** [comment]
Ah, I guess I jumped to conclusions about the project limit! I'll reach out to you via email.
