### ISSUE TITLE
Rationale for creating an account, pricing

### ISSUE THREAD

**Issue by kevinrobinson** [IBM/taxinomitis#200]
Hello, and thanks for sharing your awesome work! ❤️ 

I saw https://github.com/IBM/taxinomitis/pull/197 and was excited to check it out, so I tried making a new project for recognizing images, but ran into this:
<img width="930" alt="Screen Shot 2019-06-28 at 8 40 40 AM" src="https://user-images.githubusercontent.com/1056957/60342899-b56a0a80-9980-11e9-99a2-5626e3ff90e7.png">

I checked out https://machinelearningforkids.co.uk/#!/help and the awesomely detailed setup instructions 👍 

I was trying to understand these two pieces of information together in the sign up page, where it says "By checking this box, you accept responsibility for any fees or charges incurred on IBM Cloud" and the first question below that says "Do I have to pay for that?  No."  Reading through the detailed [setup instructions](https://github.com/IBM/taxinomitis-docs/raw/master/docs/pdf/machinelearningforkids-apikeys.pdf) it seems like the punchline is this slide:
<img width="1172" alt="Screen Shot 2019-06-28 at 8 51 12 AM" src="https://user-images.githubusercontent.com/1056957/60343486-1219f500-9982-11e9-9a03-48c82c08a0df.png">

I read this as saying that free use is severely constrained (5 text models at a time, 2 image models at a time), and that in the standard setup, IBM would bill costs for each API call to recognize text or images that comes from the Scratch apps that kids make.  Alternately, you can get standard access for no cost if you share school information with IBM.  And any approach with an account involves reading the fine print of the various legal agreements that you consent to in order to create an account (which I didn't dig into).  Does that seem like a fair summary for sharing this in conversation with other teachers?

I'm also curious if this is a technical limitation, a way to constrain costs over time, an approach to mitigate past abuses of the system, or an educational decision.  Can you share more?  Thanks again for sharing and all the hard work that comes with building things in the open. ❤️

**Comment by dalelane** [comment]
Thanks very much for getting in touch. 

> Does that seem like a fair summary for sharing this in conversation with other teachers?

I think so.

> I'm also curious if this is a technical limitation, a way to constrain costs over time, an approach to mitigate past abuses of the system, or an educational decision. Can you share more? 

Sorry, I can't really share very much about the reason for the policy/approach. 

What I've done is document the approach taken by IBM Cloud, but I have no control or influence over the process, or insight into the intentions behind it. 

The policy here, around the distinction between Lite/Standard, and the pricing of each, is not unique to Machine Learning for Kids - it's just how IBM Cloud makes its services available. 

Purely guessing, I would imagine that they do it this way because this is a good fit with developers - Lite is a free way for developers to experiment with and try out a service, and use to develop against, and Standard is intended for use when they're ready to use it in a production app. 

It's not a perfect match with a teacher wanting to try it out with 30 kids, but the Promo Codes that are provided by OnTheHub are a way to offset that. It is intended more for educational/academic use, but again - it's not a process that I have any insight into.

**Comment by kevinrobinson** [comment]
@dalelane Thanks, I really appreciate and respect your openness!

This makes me wonder if there are other ways to work around those barriers, through on-device training or inference (eg, in the browser), especially for small data sets.  I realize that's a separate bigger question though :) Thanks so much for your thoughtful response.
