### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by MobileRoboticsSchool** [IBM/taxinomitis#312]
Hello,

Thanks for your beautiful work. I noticed again something I told you in person quite a while ago: the first phase of the three phases has the title "train" while it does not correspond to training but to collecting. Would it be possible to change "train" into "collect".

Thank you,

Amaury

**Comment by dalelane** [comment]
Yes, it's possible, and if it's something that someone would like to work on, I'd be open to discussing what words would be a better choice.

I think I'm unlikely to make the change myself soon, because I think it would be a significant amount of effort for only a small benefit. 

The code change needed is small (change the string at https://github.com/IBM/taxinomitis/blob/f4a1e1613366def0c3d4e18ce75332f6dc89df7e/public/languages/en.json#L312 and in the equivalent place in the nineteen translation files (https://github.com/IBM/taxinomitis/tree/master/public/languages) 

However, it would also need updates to the instructions and screenshots in the 50+ worksheets at https://github.com/IBM/taxinomitis-docs/tree/master/project-worksheets/msword (and in the translated versions in https://github.com/IBM/taxinomitis-docs/tree/master/project-worksheets/pdf). And similarly in the Raspberry Pi projects like https://github.com/RaspberryPiLearning/alien-language https://github.com/raspberrypilearning/did-you-like-it https://github.com/raspberrypilearning/journey-to-school etc. 

I think it would take several hours to get this updated everywhere.

The reason why I think the benefit is small is because the title isn't displayed by itself, it's displayed next to a sentence providing context https://github.com/IBM/taxinomitis/blob/f4a1e1613366def0c3d4e18ce75332f6dc89df7e/public/languages/en.json#L313 
I think that when paired with that accompanying context, describing the task of collecting training examples as "training" isn't totally unreasonable, and unlikely to cause confusion. 

I'm not claiming the existing title is the best possible choice of word. But I don't think it's bad enough that it'll make it to the top of my todo list very soon.

**Comment by dalelane** [comment]
closing as inactive
