### ISSUE TITLE
When npm run build，got errors like this :should handle auth errors when storing image training:

### ISSUE THREAD

**Issue by senglez** [IBM/taxinomitis#339]
```
) REST API - training
       storeTraining()
         should handle auth errors when storing image training:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected
  {
+   error: 'Unable to download image from https://lh4.googleusercontent.com/ytIqqhmtwSe-0fG_cTnOIz4ZAQAjtbD1OcaGQ9wZ5ELUBdbie0lkivWjbSw6BCiw1sRvKUI=w371'
-   error: 'lh4.googleusercontent.com would not allow "Machine Learning for Kids" to use that image'
  }
      + expected - actual
       {
      -  "error": "Unable to download image from https://lh4.googleusercontent.com/ytIqqhmtwSe-0fG_cTnOIz4ZAQAjtbD1OcaGQ9wZ5ELUBdbie0lkivWjbSw6BCiw1sRvKUI=w371"
      +  "error": "lh4.googleusercontent.com would not allow \"Machine Learning for Kids\" to use that image"
       }
      at /home/pi/Downloads/taxinomitis/dist/tests/restapi/training.js:645:24
      at processTicksAndRejections (internal/process/task_queues.js:97:5)


Warning: Task "mochaTest:test" failed. Use --force to continue.
Aborted due to warnings.
```

Thanks for help

**Comment by dalelane** [comment]
The test still passes for me locally, and when run on Travis - e.g. https://travis-ci.org/github/IBM/taxinomitis/builds/734598943#L1306 
 
So I suspect the problem is something in your local development environment or how you're running the test. 

+ actual - expected
  {
+   error: 'Unable to download image from https://lh4.googleusercontent.com/ytIqqhmtwSe-0fG_cTnOIz4ZAQAjtbD1OcaGQ9wZ5ELUBdbie0lkivWjbSw6BCiw1sRvKUI=w371'
-   error: 'lh4.googleusercontent.com would not allow "Machine Learning for Kids" to use that image'
  }

This means the test expected to get the response "google would not allow ML for Kids to use that image" 
but actually actually got the response "unable to download image".

The expected message is returned for URLs that return a permission error
https://github.com/IBM/taxinomitis/blob/a08e8f264160cd7e91fc1468ad6caf4f8178bb18/src/lib/utils/download.ts#L100-L104 

The message that was returned when you ran it meant it ended up here
https://github.com/IBM/taxinomitis/blob/a08e8f264160cd7e91fc1468ad6caf4f8178bb18/src/lib/utils/download.ts#L109

The logs/ml-for-kids.log will contain the detailed response that is logged from
https://github.com/IBM/taxinomitis/blob/a08e8f264160cd7e91fc1468ad6caf4f8178bb18/src/lib/utils/download.ts#L108 

Please can you provide the detailed response.

**Comment by dalelane** [comment]
_(This is the third place you've asked this question - please stop cross-posting this question into multiple places. I had already replied to the other two!)_
