### ISSUE TITLE
[Request] Image Upload via File Picker

### ISSUE THREAD

**Issue by FunkMonkey** [IBM/taxinomitis#482]
It would be nice if additionally to Image URLs, Webcam and Drawings, images could also be uploaded via a file picker! Especially on mobile devices, the adding of images via URLs is quite cumbersome and an alternative would be appreciated. 
Given that webcam and drawings already send images to the server, I assume there wouldn't be much development work...

Thanks!

**Comment by dalelane** [comment]
Sorry - this was an intentional decision. Essentially, storing image files is super expensive. I don't want to encourage it. 

Yes, making users store an image somewhere else and then give me a short string URL to store is absolutely a bit of a hassle for them. But it's orders of magnitude cheaper from my running costs perspective. 

You're right to point out that I've made an exception for drawings and webcam... and that was a difficult decision to make. Ultimately I'm taking the storage costs hit to enable projects that otherwise couldn't be done. But storing other images is harder to justify in that way.

**Comment by dalelane** [comment]
Yeah - that's perfectly reasonable. To be honest, I'm naturally less motivated to work on features that I'm not going to use myself, so while I don't object to it, I should be clear that it's unlikely this would make it to the top of my todo list any time soon.

**Comment by dalelane** [comment]
I've added this now for [local projects](https://dalelane.co.uk/blog/?p=5042) where I don't need to worry about the storage implications 

https://github.com/IBM/taxinomitis/commit/8511b295f1c6f87f23287f74663ede4628131277
