### ISSUE TITLE
Watson or Watsonx

### ISSUE THREAD

**Issue by AndreaRocca** [IBM/taxinomitis#498]
I tried to create an API with Watsonx and it asks for a credit card. Is there a way to create an API without having to give sensitive data to IBM?

**Comment by dalelane** [comment]
Most ways of using the Machine Learning for Kids website do not require an API key for Watson Assistant. 

Most significantly, Watson Assistant API keys can only be used for projects that recognise **text**
 
Watson Assistant API keys are not related to:
- projects that recognise **numbers**
- projects that recognise **sounds**
- projects that recognise **images**
- projects that predict **numbers**
- projects that use **pretrained** models 
 
For projects that recognise text, there are multiple ways to be able to create a project that don't require you to create your own Watson Assistant API key.

This is described in more detail at https://groups.google.com/g/mlforkids/c/bS9nooCdiyw 

If you choose an option that does require an Watson Assistant API key, this repo isn't the best place to get support. Mostly because I don't closely follow the processes they have, and they change over time. Questions about Watson Assistant are really best directed to the IBM Cloud team that supports the service at https://www.ibm.com/products/watsonx-assistant

I would observe, however, that looking quickly at the site now, "No credit card required" is the first message on their sign up page, so my guess is that it is probably possible to sign up without a credit card. But I really can't comment any further on it, sorry. 

![image](https://github.com/user-attachments/assets/1a6dfa53-672a-4115-8c18-2995be154ab6)

**Comment by AndreaRocca** [comment]
Thank you for taking the time to explain this in detail. I really appreciate the information about using Watson Assistant API keys and the distinction between different types of projects. It's very helpful to know that there are options available for text recognition projects that don't require a personal API key, and that for other cases it's best to reach out directly to the IBM Cloud support team.

I'll check out the link you provided and consider the options available for my project. Thanks again for your help and guidance.
